name: Update Contributors

# Schedule: Runs at midnight on the first day of each month
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # At 00:00 UTC on the 1st of every month

jobs:
  update-contributors:
    runs-on: debian-01

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # Run the update script
    - name: Install python yaml
      run: pip install pyyaml

    - name: Run update-contributors script
      run: |
        python3 /etc/update-contributors.py

    # Configure Git for the PR
    - name: Set up Git
      run: |
        git config user.name "contributor-list[bot]"
        git config user.email "contributor-list[bot]@users.noreply.github.com"

    # Commit the changes
    - name: Commit Changes
      run: |
        git add _data/people_list.yml
        git commit -m "Update contributors on $(date +'%Y-%m-%d')" || echo "No changes to commit" && false

    # Create a pull request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Update contributors on $(date +'%Y-%m-%d')"
        branch: update-contributors
        title: "Update contributors"
        body: |
          This PR updates the contributors list based on the latest changes.
